aws-lambda-python/README.md, aws-lambda-python/lambda_function.py
Tested on lambda AND cloud9 lambda
Works perfectly, messages arrive and all is green!
=> Updated python lambda for decorator change

java-aws-elasticbeanstalk/README.md, java-aws-lambda-maven/README.md, java-aws-lambda/README.md, java-docker-compose/README.md, java-dropwizard/README.md, java-gradle/README.md, java-groovy/README.md, java-maven/README.md, java-tomcat-aws-elasticbeanstalk/README.md, java-weblogic/README.md, java-wildfly-docker-agentless/README.md
Phrasing improvements.
Removed specific mentions of "agentless" in cases where example is agentless.
In the same cases, removed mention of host and port configuration.
=> Readme.md phrasing cleanup - Java examples

python-aws-chalice/Readme.md, python-aws-lambda/README.md, python-aws-serverlessframework/README.md, python-django/README.md, python-flask/README.md, python-kubernetes/README.md
Phrasing suggestions
Removed direct mentions to Agentless
Remove host and port environment variables
=> Readme cleanup python examples

java-aws-elasticbeanstalk/README.md, java-aws-lambda-maven/README.md, java-aws-lambda/README.md, java-docker-compose/README.md, java-dropwizard/README.md, java-gradle/README.md, java-groovy/README.md, java-maven/README.md, java-play-framework/2.5.x/README.md, java-play-framework/2.6.x/README.md, java-tomcat-aws-elasticbeanstalk/README.md, java-weblogic/README.md, java-wildfly-docker-agentless/README.md, node-app-engine-flex/README.md, node-aws-ecs/README.md, node-aws-elasticbeanstalk/README.md, node-aws-lambda/README.md, node-electron/README.md, node-ibm-cloud-functions/README.md, node-typescript/README.md, python-aws-chalice/Readme.md, python-aws-lambda/README.md, python-aws-serverlessframework/README.md, python-django/README.md, python-flask/README.md, python-kubernetes/README.md
=> Contact us in untested deployment exmaples

java-aws-elasticbeanstalk/README.md, java-aws-lambda-maven/README.md, java-aws-lambda/README.md, java-docker-compose/README.md, java-gradle/README.md, java-groovy/README.md, java-maven/README.md, java-tomcat-aws-elasticbeanstalk/README.md, java-weblogic/README.md, java-wildfly-docker-agentless/README.md, node-app-engine-flex/README.md, node-aws-ecs/README.md, node-aws-elasticbeanstalk/README.md, node-aws-lambda/README.md, node-electron/README.md, node-typescript/README.md, python-aws-lambda/README.md, python-aws-serverlessframework/README.md, python-django/README.md, python-flask/README.md
https://github.com/Rookout/Rookout/issues/2574
=> fix broken links to old rook pages

node-typescript/README.md, node-typescript/package.json
* Updating Rookout version in package.json (0.1.20)
* Updating README.md file - delete agent setup
=> Node typescript update

java-aws-elasticbeanstalk/README.md, java-aws-lambda-maven/README.md, java-gradle/README.md, java-groovy/README.md, java-maven/README.md, java-play-framework/2.5.x/README.md, java-play-framework/2.6.x/README.md, java-tomcat-aws-elasticbeanstalk/README.md, java-weblogic/README.md, java-wildfly-docker-agentless/README.md, node-app-engine-flex/README.md, node-aws-ecs/README.md, node-aws-elasticbeanstalk/README.md, node-aws-lambda/README.md, node-electron/README.md, node-typescript/README.md, python-aws-lambda/README.md, python-aws-serverlessframework/README.md, python-django/README.md, python-flask/README.md, python-kubernetes/README.md
=> RK-534 Rook to Rookout SDK

java-dropwizard/README.md, java-weblogic/README.md, python-flask/README.md
=> RK-520 - Deployment Examples

java-aws-elasticbeanstalk/README.md, java-aws-lambda-maven/README.md, java-aws-lambda/README.md, java-docker-compose/README.md, java-groovy/README.md, java-play-framework/2.5.x/README.md, java-play-framework/2.6.x/README.md, java-tomcat-aws-elasticbeanstalk/README.md, java-weblogic/README.md, java-wildfly-docker-agentless/README.md, node-app-engine-flex/README.md, node-aws-ecs/README.md, node-aws-elasticbeanstalk/README.md, node-electron/README.md
=> RK-513 Agent to ETL Agent

python-aws-serverlessframework/Jenkinsfile, python-aws-serverlessframework/handler.py
This reverts commit ded06ccdf9f217045c53925d59ae3bb40354e277.
=> RK-2896 - Revert "fixing test (#121)"

java-docker-compose/README.md, java-docker-compose/docker-compose.yaml, java-maven/maven-agent/README.md
=> RK-3940 - Added message about updating maven.compiler properties

java-maven/maven-perforce/Dockerfile, java-maven/maven-perforce/Jenkinsfile, java-maven/maven-perforce/README.md, java-maven/maven-perforce/pom.xml, java-maven/maven-perforce/src/main/java/com/rookout/HelloWorld.java
See Readme and pom.xml
Tested locally.
=> RK-5801 - Added maven-perforce instructions

java-maven/maven-git/Dockerfile, java-maven/maven-git/README.md, java-maven/maven-git/pom.xml, java-maven/maven-git/src/main/java/com/rookout/HelloWorld.java
=> RK-5826 - Maven/git

java-maven/maven-perforce-existing-jar/Dockerfile, java-maven/maven-perforce-existing-jar/README.md, java-maven/maven-perforce-existing-jar/pom.xml, java-maven/maven-perforce-existing-jar/src/main/java/com/rookout/HelloWorld.java
Adding another method of updating the manifest.
This is a less "intrusive" way of updating the manifest, as it updates an existing JAR's manifest rather then being a part of the build/package process.
=> RK-5937 - Adding another method of updating an existing JAR

java-maven/maven-git/README.md, java-maven/maven-perforce-existing-jar/README.md, java-maven/maven-perforce/README.md
Applies Rookout/docs#354 to deployment examples.
=> RK-6553 - Fix path to rook.jar in -javaagent options in docs.

node-typescript/Dockerfile, node-typescript/Jenkinsfile, node-typescript/src/app.ts
https://rookout.atlassian.net/browse/RK-6651
=> RK-6551 - Changed node-typescript regression test into a server

node-14/Dockerfile, node-14/Jenkinsfile, node-14/package.json, node-14/src/app.js
https://rookout.atlassian.net/browse/RK-6589
=> RK-6589 - add node 14 regression test

aws-ecs/Makefile, aws-ecs/README.md, aws-ecs/controller_task_def.tpl, aws-ecs/dop_task_def.tpl, aws-ecs/main.tf
This example using terraform to setup ECS cluster and install DOP & Controller on it.
=> RK-8437 - ECS deployment example

java-wildfly-docker/README.md
=> RK-8866 - Update README.md

node-aws-lambda/Dockerfile, node-webpack/Readme.md
https://rookout.atlassian.net/browse/RK-6653
=> RK-6653 - Change node-webpack Readme title

java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/runTest.sh
=> RK-9916 - fix tomecat aws test run options

node-typescript/package.json, node-typescript/tsconfig.json
fixing https://github.com/Rookout/deployment-examples/pull/261
=> fix ts example (RK-10263)

java-gradle/java-dynamic-loading/Jenkinsfile
need a bit more time because we parse a lot of scripts
=> RK-11382 - add more time for dynamic loading

java-gradle/java-dynamic-loading/Jenkinsfile
=> RK-11385 - remove custom time

java-aws-lambda-maven/README.md, java-aws-lambda-maven/jar-with-dependencies.xml, java-aws-lambda-maven/pom.xml
=> RK-11830 - Fixed JVM lambda maven

java-aws-elasticbeanstalk/runTest.sh, java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/runTest.sh, node-aws-elasticbeanstalk/node-example/runTest.sh, node-aws-lambda/awsTest.sh, node-aws-serverlessframework/runTest.sh, python-aws-chalice/.chalice/config-reg-test.json, python-aws-lambda/awsTest.sh, python-aws-serverlessframework/testEnvs.sh
Reverts Rookout/deployment-examples#308
=> Revert "RK-14312 - deprecate tags for regression tests"

java-gradle/java-dynamic-loading/runTest_workflow.sh
=> RK-14705 - java dynamic loading test script fix

.jenkins/Jenkinsfile
- remove of java reg test from jenkins
- skip regtest for java
=> RK-18586 - ignore java regression test
